
package igu;

import javax.swing.JOptionPane;
import logica.Controladora;



public class Principal extends javax.swing.JFrame {
    //Creo la variable global controla de tipo Controladora
    Controladora controla;
    
    //Le paso el parametro de la controladora a la interfaz gráfica.
    public Principal(Controladora controla) {       
        initComponents();
        this.controla = controla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblAlergico = new javax.swing.JLabel();
        lblAtencion = new javax.swing.JLabel();
        lblNombreDuenio = new javax.swing.JLabel();
        lblCelu = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        cmbAlergico = new javax.swing.JComboBox<>();
        cmbAtencionEspecial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtNroCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtNombreDuenio = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setText("Peluquería Canina");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 37));

        lblCliente.setText("Cliente Nº:");
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 118, -1, -1));

        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 161, -1, -1));

        lblRaza.setText("Raza:");
        jPanel1.add(lblRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 203, -1, -1));

        lblColor.setText("Color:");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 245, -1, -1));

        lblAlergico.setText("Alergico:");
        jPanel1.add(lblAlergico, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 288, -1, -1));

        lblAtencion.setText("Atención Especial:");
        jPanel1.add(lblAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 326, -1, -1));

        lblNombreDuenio.setText("Nombre Dueño:");
        jPanel1.add(lblNombreDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 363, -1, -1));

        lblCelu.setText("Celu. del Dueño:");
        jPanel1.add(lblCelu, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 399, -1, -1));

        lblObservaciones.setText("Observaciones:");
        jPanel1.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 431, -1, -1));

        cmbAlergico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        cmbAlergico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cmbAlergico, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 283, 65, -1));

        cmbAtencionEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        jPanel1.add(cmbAtencionEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 321, 61, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 431, 262, 154));

        txtNroCliente.setEditable(false);
        txtNroCliente.setText("(Autogenerado)");
        txtNroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 114, 261, -1));

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 157, 261, -1));

        txtRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 199, 260, -1));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 241, 260, -1));

        txtNombreDuenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDuenioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 359, 262, -1));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 395, 262, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-erase-32.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, -1, 42));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-32.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, 42));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 127, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dgroom.com.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 300, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bubbles2m.com_50.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 280, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Tomo los atributos de los textFields
        
        String nombreCliente=txtNombreCliente.getText();
        String raza=txtRaza.getText();
        String color=txtColor.getText();
        String alergico=(String) cmbAlergico.getSelectedItem();
        String atencion=(String) cmbAtencionEspecial.getSelectedItem();
        String nombreDuenio= txtNombreDuenio.getText();
        String celular=txtCelular.getText();
        String observaciones=txtObservaciones.getText();
        
        //Intenta enviar los datos a la logica mediante la controladora
        try{
            controla.crearMascota(nombreCliente,raza,color,alergico,atencion,nombreDuenio,celular,observaciones);
            JOptionPane.showMessageDialog(rootPane, "Se guardó el cliente", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);

        }catch (Exception r){
            JOptionPane.showMessageDialog(rootPane, "No se pudo guardar el Cliente","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Borra los textFields y los combobox los pone a indice 0
       
        txtNombreCliente.setText("");
        txtRaza.setText("");
        txtColor.setText("");
        cmbAlergico.setSelectedIndex(0);
        cmbAtencionEspecial.setSelectedIndex(0);
        txtNombreDuenio.setText("");
        txtCelular.setText("");
        txtObservaciones.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroClienteActionPerformed

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void txtNombreDuenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDuenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDuenioActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbAlergico;
    private javax.swing.JComboBox<String> cmbAtencionEspecial;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlergico;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblCelu;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreDuenio;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreDuenio;
    private javax.swing.JTextField txtNroCliente;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
